name: Repo Data & figures

on:
  schedule:
    - cron: '15 22 * * *' # Runs 1st, 11th, and 21st of every month 0 0 1,11,21 * *
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install requests pandas matplotlib seaborn

    - name: Run script
      working-directory: ./script  # Set working directory
      env:
        OWNER: 'demidenm'  # GitHub repo owner
        REPO: 'PyReliMRI'  # GitHub repo name
        MY_ACCESS_TOKEN: ${{ secrets.REPO_A_ACCESS_TOKEN }} # Settings -> Secrets and variables -> Actions -> New Repository secret
      run: |
        python repo_check-traffic.py